server:
  port: 8181

spring:
  datasource:
    #jdbc-url: jdbc:mysql://localhost:9906/user_management
    url: jdbc:mysql://localhost:9906/php-app
    username: USER
    password: PASS
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: create-drop